#!/usr/bin/env bash
# A script that runs nginx as nginx user and listens on all active IP addresses on port 8080.
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
