#!/usr/bin/env bash
# Using what you did in Task #1, I made the fix short and sweet.
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
